### ISSUE TITLE
Support for real-valued features

### ISSUE THREAD

**Issue by ddahlmeier** [pystruct/pystruct#157]
Is it possible to use real-valued, continuous features in pystruct or this this planned for the future road-map?

**Comment by amueller** [comment]
The features are assumed to be real-valued. There are actually no categorical features.
The labels are all categorical, though.

**Comment by ddahlmeier** [comment]
Thanks for the reply. 

In my case, I have continuous-valued features, for example temperature. When I use the raw feature values, I get very poor performance, binning and binarizing the features improved the performance. Is this just an artifact or do I need to do some pre-preocessing to my raw feature values?

**Comment by amueller** [comment]
the structured svm is "linear" in the features. I put it in quotes because the result is not linear, the potentials are linear. But if the temperature has very non-linear interactions, then this will likely not work.
You can try binning or encoding using a random forest (my favourite method, see https://github.com/scikit-learn/scikit-learn/pull/5037) or training a non-linear classifier and then using the output

**Comment by amueller** [comment]
closing as not really an issue.
